### ISSUE TITLE
List of available models and parameters

### ISSUE THREAD

**Issue by JonasMedu** [Aleph-Alpha/aleph-alpha-client#141]
Where can i find a list of all **available models** and their respective **maximum input tokens**?

I am looking for names i can pass to the `client.complete` function. Furthermore i want to create an assert which ensures me that the request will be safe within the token length.

```python
from aleph_alpha_client import Client, CompletionRequest
client = Client(token=os.getenv("AA_TOKEN"))
request = CompletionRequest(prompt='What is green?', maximum_tokens=100)
for model_name in model_name_list:
    #todo: assert my_token_length_check(request.get_prompt()), f"Input to long for {model_name}"
    response = client.complete(request=request, model=model_name)
    completion = response.completions[0].completion
    print(completion)
```

**Comment by timsueberkrueb** [comment]
Hey @JonasMedu,

you can get a list of available models by using the [`Client.models`](https://aleph-alpha-client.readthedocs.io/en/latest/aleph_alpha_client.html#aleph_alpha_client.Client.models) method:

```python
model_list = client.models()
```

For each available `model` in `model_list`, consider the following fields:

```python
model_name = model["name"]
maximum_completion_tokens = model["maximum_completion_tokens"]
max_context_size = model["max_context_size"]
```

To get the length of your prompt in tokens, you can tokenize the prompt as follows:

```python
tokenizer = client.tokenizer(model=model_name)
n_input_tokens = len(tokenizer.encode(prompt_text).ids)
```

If you want to complete the maximum number of tokens, you can calculate the maximum size of input tokens as follows:

```python
max_input_tokens = max_context_size - maximum_completion_tokens
```

However, you can also reduce the number of completion tokens to increase the number of input tokens by setting the `maximum_tokens` parameter on `CompletionRequest`.

**Comment by ahartel** [comment]
Thanks @timsueberkrueb for answering this question. @JonasMedu let us know if you have follow-up questions, feel free to re-open the issue if that is the case. Closing it for now.
