### ISSUE TITLE
Getting a 403 whenever trying to use multimodal image prompting

### ISSUE THREAD

**Issue by jonico** [Aleph-Alpha/aleph-alpha-client#170]
👋 In the past, I was able to run my sample "Find Waldo example" based on your SDK, but today I only get a 403, also with different pictures. The provided token works for ordinary completions without an image prompt.

Sample code:

```python

import os
from aleph_alpha_client import Client, Prompt, CompletionRequest, Image

client = Client(token=os.getenv("AA_TOKEN"))

#This method can use many types of objects, local path str, local path Path object or bytes array
#image_source = "/path/to/my/image.png"
#image_source = Path("/path/to/my/image.png")
image_source = "https://user-images.githubusercontent.com/1872314/261075980-cfcadfed-8792-4045-9382-55f65c13a7a3.png"

image = Image.from_image_source(image_source=image_source)

# have a second image
image_source2 = "https://user-images.githubusercontent.com/1872314/261072701-5e608b8a-3df1-4fe7-9869-24aaf2bc4a81.png"
image2 = Image.from_image_source(image_source=image_source2)


prompt = Prompt(
    items=[
        image,
        "This is Waldo",
        image2,
        "Q: Can you find Waldo from the first picture on the second picture and if so, where exactly and can you also tell me whether a table is close to Waldo? A:",
        #"Q: What kind of train do you see on the picture? Can you tell its type and its color? A:",
    ]
)
params = {
    "prompt": prompt,
    "maximum_tokens": 128,
    "stop_sequences": [],
    "temperature": 0.5,
    #"minimum_tokens": 16
}
request = CompletionRequest(**params)
# set python http request proxy to https://127.0.0.1:5555 by setting the environment variable HTTPS_PROXY
#os.environ["https_proxy"] = "http://localhost:5555"

response = client.complete(request=request, model="luminous-extended")
completion = response.completions[0].completion

print(completion)

```

**Comment by pacman82** [comment]
Hello @jonico ,

did you by any chance create a new account an our API. To prevent abuse of our multi-modality features we deactivated it for public signers (i.e. non-buisness users) of our API. If I know your email (the one you used to create the AA account). I could activate the feature again for you, though.

Does our models actually find waldo? Seems like a neat example.

Best, Markus

**Comment by pacman82** [comment]
I reached out to you on LinkedIn, so you can share your mail with me, without the rest of the internet being able to read it.

**Comment by jonico** [comment]
I followed up with you on LinkedIn, also I created my account mid of last year

> Does our models actually find waldo? Seems like a neat example.

Well, sometimes, sometimes not :-) I created a [Postman workspace for Aleph Alpha](https://www.postman.com/automotive-demo/workspace/aleph-alpha/collection/24483733-f8fe5e20-04e6-467e-acf9-3bafe5cbe17e) a while back with some examples, including finding Waldo.

![image](https://github.com/Aleph-Alpha/aleph-alpha-client/assets/1872314/fc47676d-8761-44e5-8ed0-88b16d17736a)

**Comment by jonico** [comment]
![image](https://github.com/Aleph-Alpha/aleph-alpha-client/assets/1872314/6fa4ed46-b381-488b-bfa4-196080fc0a18)

@pacman82 works again 🎉 - maybe a different status code in case for disabled features would make more sense in the future 😉

**Comment by pacman82** [comment]
Happy it works again for you, and what it did find Waldo. `403` is not completely wrong as it is indeed about permission to access the feature. We could try to accompany it with a better error message though.
