### ISSUE TITLE
No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by To3No7** [Aleph-Alpha/aleph-alpha-client#24]
When trying to run your code example in colab I get:

```
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-9-eb27f3a312b1>](https://localhost:8080/#) in <module>()
----> 1 from aleph_alpha_client import ImagePrompt, AlephAlphaClient
      2 
      3 client = AlephAlphaClient(
      4     host="https://api.aleph-alpha.com/",
      5     token="<your token>"

1 frames

[/usr/local/lib/python3.7/dist-packages/aleph_alpha_client/aleph_alpha_client.py](https://localhost:8080/#) in <module>()
      1 from typing import List, Optional, Dict, Union
----> 2 from importlib.metadata import version
      3 
      4 import requests
      5 import logging

ModuleNotFoundError: No module named 'importlib.metadata'
```

Trying to pip install importlib or importlib-metadata do not help.

**Comment by pacman82** [comment]
Hello @To3No7 ,

thanks for giving the API a spin. Not sure what exactly is going on here, but at least I do not think that we need the `importlib` dependency at all. We currently just use it to parse the API version of the service.

Cheers, Markus

**Comment by To3No7** [comment]
It seems that there is a change in version 3.10 of this library "Changed in version 3.10: importlib.metadata is no longer provisional." https://docs.python.org/3/library/importlib.metadata.html
It seems that functionality is taken over by importlib-metadata https://github.com/python/importlib_metadata , but I do not know how to program your usage of this to cope with various versions of python and these libraries.

Will you update aleph_alpha_client.py so that it no longer depend on this library?

**Comment by pacman82** [comment]
This is my intention. If my current understanding is correct, we only actually use the `version` type of this library to parse a version string of the http API in order to inform users that they may want to update the client in case the API has changed in a non backwards compatible manner.

Basically I think the use of this package can be replaced with a `split`.

**Comment by jneuff** [comment]
Hi @To3No7,

we removed our dependency on `importlib.metadata`. A colleague just tested the latest release 1.4.2 in google colab and it worked. Please let us know, if you run into fuirther problems.
