### ISSUE TITLE
API not accepting `pooling` to be `null` in Embedding function

### ISSUE THREAD

**Issue by pblan** [Aleph-Alpha/aleph-alpha-client#29]
The API itself doesn't allow `null` to be a valid input for `pooling`.
This is in contradiction to the docs found at [https://docs.aleph-alpha.com/api/#/paths/~1embed/post ](https://docs.aleph-alpha.com/api/#/paths/~1embed/post)

> pooling | Array of strings or null 
> Pooling operation to use. No pooling is used (an embedding per input token is returned) if None.

Example cURL-command:
```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer {...}" -d '{"model": "luminous-base", "prompt": "This issue will be fixed.", "layers": [-1], "pooling": null}' https://api.aleph-alpha.com/embed
```

**Comment by pacman82** [comment]
Hi @pblan ,

you are completely right. Contrary to the documentation pooling is a required parameter. Thanks for bringing that to our attention, and sorry for the inconvenience.

Cheers, Markus

**Comment by pblan** [comment]
Thanks @pacman82 for the insanely fast response!

Any idea when this will be fixed?

**Comment by pacman82** [comment]
Hello @pblan ,

just wanting to clarify. As you might have seen we fixed our documentation, but you probably intended for us to support embeddings without them being aggregated using a pooling operation (is this assumption right?).

If so, I can not just implement it, I would need to asks some persons nicely, and also provide them with a reason to do that (i.e. your usecase).

Cheers, Markus

**Comment by pacman82** [comment]
Closing this issue, please reopen if you can describe your usecase.

**Comment by pblan** [comment]
@pacman82 Please excuse the missing response! Exams are near and I got pretty busy. 🥲 

The use case would've been to train some classifiers/regressors on the embeddings (or combined with embeddings from other (pretrained) models) to some corresponding tasks.
The non-pooled embeddings would've been nice, since they are so exhaustive!

I totally understand that it's not possible without an important need!

Thank you for the interaction in any case!

**Comment by ahartel** [comment]
Closing this issue for now, since there hasn't been any update for more than a year.
