### ISSUE TITLE
Client not working in Google Colab due to python Versioning

### ISSUE THREAD

**Issue by MarkusSchmitz** [Aleph-Alpha/aleph-alpha-client#51]
### Issue: 
The aleph-alpha-client is currently not working in a google colab environment.
While the client is installable, when importing the client with embeddings, an import error occurs:

```sh
[/usr/local/lib/python3.7/dist-packages/aleph_alpha_client/embedding.py](https://localhost:8080/#) in <module>
      1 from enum import Enum
----> 2 from typing import (
      3     Any,
      4     Dict,
      5     List,

ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)

```

This seems to be an issue with Colab running on 3.7 and "typing" requiring 3.8.

### Steps to reproduce:
- Open Colab
- run: 
```python
!pip install aleph-alpha-client
from aleph_alpha_client import AlephAlphaModel, AlephAlphaClient, CompletionRequest, Prompt
```

**Comment by ahartel** [comment]
Hi Markus, seems to be an issue with importing Literal from typing, which was only introduced in Python 3.8.
I think this can be solved by using an Enum instead.
Since supporting Google Colab has been a goal in the past, I think it makes sense to provide a fix. Working on it

**Comment by pacman82** [comment]
Please verify this assumption:

* Supporting google colab implies supporting Python 3.7

If the assumption turns out to be true:

* Test against Python 3.7

**Comment by ahartel** [comment]
PR has been merged and it should work now in Google Colab. Thanks for reporting 👍

**Comment by MarkusSchmitz** [comment]
There still seems to be an issue with colab in specific:
```sh
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-bd094b3dcff6>](https://localhost:8080/#) in <module>
      1 model = AlephAlphaModel(
----> 2     AlephAlphaClient(host="https://api.aleph-alpha.com/", token="123"),
      3     model_name = "luminous-extended"
      4 )

[/usr/local/lib/python3.7/dist-packages/aleph_alpha_client/aleph_alpha_client.py](https://localhost:8080/#) in __init__(self, host, token, email, password, request_timeout_seconds)
     66             status_forcelist=[408, 429, 500, 502, 503, 504],
     67             allowed_methods=["POST", "GET"],
---> 68             raise_on_status=False,
     69         )
     70         adapter = HTTPAdapter(max_retries=retry_strategy)

TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

This doesn't seem to be an issue with the version of python but with urllib or requests. They probably need to be fixed to a specific version, where "allowed methods" was introduced.

**Comment by pacman82** [comment]
Works now in Google Colab without explicitly upgrading urllib `2.4.3`.
