### ISSUE TITLE
DetokenizationResponse member "result" should be typed as str instead of Sequence[str]

### ISSUE THREAD

**Issue by BlueCrescent** [Aleph-Alpha/aleph-alpha-client#79]
Hello everyone,

while technically a str is also a Sequence[str], in the following code the filed result should be treated as a str (as specified in the corresponding [docs](https://docs.aleph-alpha.com/api/detokenize/)):

https://github.com/Aleph-Alpha/aleph-alpha-client/blob/7d9e873a8c79758e394b14b9495d102c3c48c811/aleph_alpha_client/detokenization.py#L22-L23

**Comment by pacman82** [comment]
@BlueCrescent Thanks for reporting this issue. @volkerstampa Could you fix this?

**Comment by volkerstampa** [comment]
@BlueCrescent Thanks for the hint. Just fixed it. Will be released with the next release.

**Comment by volkerstampa** [comment]
@BlueCrescent Released as v2.9.2
